name: Update Movies Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install requests

      - run: python update_movies.py

      - name: Commit Movies Playlist
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Movies_All.m3u
          git commit -m "Update Movies Playlist" || exit 0
          git push
